### ISSUE TITLE
Failed to download resources

### ISSUE THREAD

**Issue by TingxunShi** [gpengzhi/CrossConST-SR#1]
Hi, I followed the url provided in `MuSR/musr_embedding/musr.py` to try to download the resources. However, Google Drive reported an error, saying "您需要访问权限". I also tried to download them via `gdown`, and exception `SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)` was raised. Could you please kindly to check? Thank you

**Comment by gpengzhi** [comment]
Thank you for your interest in `MuSR`!

We fixed the downloading issue. Please try again, and we are looking forward to your feedback.
